import { runCopilotPrompt, MODELS } from "./github-models.client";
import { CoreSummary, FinancialGoalOutput } from "../types/agent.types";

const SYSTEM_PROMPT = `
You are a personal financial advisor AI at a bank called StatementIQ.
You will be given a customer's financial health summary generated by another AI agent.

Based on this summary, generate personalized financial goals for this customer.
Return ONLY a valid JSON array with the following structure:
[
  {
    "title": <string: short goal name>,
    "description": <string: clear explanation of the goal and why it matters for this customer>,
    "targetAmount": <number or null>,
    "timeline": <"short" | "medium" | "long">,
    "monthlySavings": <number: suggested monthly contribution or null>,
    "priority": <number: 1 is highest priority>
  }
]

Timeline definitions:
- "short": 0-6 months
- "medium": 6-24 months
- "long": 2+ years

Guidelines:
- Generate 2 short-term goals, 2 medium-term goals, and 1 long-term goal (5 total).
- Make goals SPECIFIC to the customer's actual financial data — reference their income, expenses, loans.
- Order by priority (1 = most urgent).
- Return ONLY the JSON array. No extra text, no markdown, no code blocks.
`.trim();

export async function runFinancialGoalAgent(
  summary: CoreSummary
): Promise<FinancialGoalOutput[]> {
  console.log("[FinancialGoalAgent] Generating personalized goals...");

  const raw = await runCopilotPrompt(
    SYSTEM_PROMPT,
    JSON.stringify(summary),
    MODELS.SMART
  );

  // Strip markdown code fences if present
  const jsonStr = raw.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "").trim();

  const parsed = JSON.parse(jsonStr);
  const goals: FinancialGoalOutput[] = Array.isArray(parsed)
    ? parsed
    : parsed.goals ?? [];

  console.log(`[FinancialGoalAgent] Generated ${goals.length} goals`);
  return goals;
}